DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (ID INT AUTO_INCREMENT PRIMARY KEY, LOGIN VARCHAR(250) NOT NULL, PASSWORD VARCHAR(250) NOT NULL);

INSERT INTO `USERS` (LOGIN, PASSWORD) VALUES ('admin', 'admin');