CREATE TABLE SF_USERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SF_FORMS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES SF_USERS(ID)
);

CREATE TABLE SF_FORM_FIELDS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    FIELD_TYPE_ID INT NOT NULL,
    LABEL VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    STATUS ENUM('ACTIVE', 'INACTIVE', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
    FOREIGN KEY (FORM_ID) REFERENCES SF_FORMS(ID),
    FOREIGN KEY (FIELD_TYPE_ID) REFERENCES SF_FORM_FIELD_TYPES(ID),
    CHECK (STATUS IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE TABLE SF_FORM_FIELD_TYPES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    TEMPLATE TEXT NOT NULL
);

CREATE TABLE SF_FORM_FIELD_PARAMETERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_FIELD_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_FIELD_ID) REFERENCES SF_FORM_FIELDS(ID)
);

CREATE TABLE SF_FORM_FIELD_OPTIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FIELD_ID INT NOT NULL,
    OPTION_VALUE VARCHAR(255) NOT NULL,
    OPTION_LABEL VARCHAR(255) NOT NULL,
    FOREIGN KEY (FIELD_ID) REFERENCES SF_FORM_FIELDS(ID)
);

CREATE TABLE SF_FORM_RESPONSES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FORM_ID) REFERENCES SF_FORMS(ID)
);

CREATE TABLE SF_FORM_FIELD_RESPONSES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_RESPONSE_ID INT NOT NULL,
    FORM_FIELD_ID INT NOT NULL,
    VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_RESPONSE_ID) REFERENCES SF_FORM_RESPONSES(ID),
    FOREIGN KEY (FORM_FIELD_ID) REFERENCES SF_FORM_FIELDS(ID)
);

CREATE TABLE SF_FORM_CONFIG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    CONFIG_NAME VARCHAR(255) NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_ID) REFERENCES SF_FORMS(ID)
);

CREATE TABLE SF_FORM_FIELD_CONFIG (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_FIELD_ID INT NOT NULL,
    CONFIG_NAME VARCHAR(255) NOT NULL,
    CONFIG_VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_FIELD_ID) REFERENCES SF_FORM_FIELDS(ID)
);

CREATE TABLE SF_FORM_DEFAULT_VALUES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID INT NOT NULL,
    FIELD_ID INT NOT NULL,
    DEFAULT_VALUE TEXT NOT NULL,
    FOREIGN KEY (FORM_ID) REFERENCES SF_FORMS(ID),
    FOREIGN KEY (FIELD_ID) REFERENCES SF_FORM_FIELDS(ID)
);